# Exploratory analysis

In [4]:
import polars as pl
from refactor import analysis
from refactor.analysis import condition_accuracy


# Load sample data and display a few trials
df = analysis.get_sample_data()
df.head()

shape: (5, 3)
┌───────┬───────────┬─────────┐
│ trial ┆ condition ┆ correct │
│ ---   ┆ ---       ┆ ---     │
│ i64   ┆ i64       ┆ i64     │
╞═══════╪═══════════╪═════════╡
│ 1     ┆ 1         ┆ 0       │
│ 2     ┆ 1         ┆ 0       │
│ 3     ┆ 1         ┆ 1       │
│ 4     ┆ 1         ┆ 1       │
│ 5     ┆ 1         ┆ 0       │
└───────┴───────────┴─────────┘

In [5]:



# Calculate accuracy in each condition
m = condition_accuracy(df)
m

shape: (2, 2)
┌───────────┬──────────┐
│ condition ┆ correct  │
│ ---       ┆ ---      │
│ i64       ┆ f64      │
╞═══════════╪══════════╡
│ 1         ┆ 0.466667 │
│ 2         ┆ 0.6      │
└───────────┴──────────┘

In [6]:
from datascipsych import datasets
file = datasets.get_dataset_file("Morton2013")
fr_data = pl.read_csv(file, null_values="n/a")
fr_data.head()

shape: (5, 15)
┌─────────┬─────────┬──────┬──────────┬───┬───────────────┬──────────┬──────────┬───────────────┐
│ subject ┆ session ┆ list ┆ item     ┆ … ┆ list_category ┆ category ┆ response ┆ response_time │
│ ---     ┆ ---     ┆ ---  ┆ ---      ┆   ┆ ---           ┆ ---      ┆ ---      ┆ ---           │
│ i64     ┆ i64     ┆ i64  ┆ str      ┆   ┆ str           ┆ str      ┆ i64      ┆ f64           │
╞═════════╪═════════╪══════╪══════════╪═══╪═══════════════╪══════════╪══════════╪═══════════════╡
│ 1       ┆ 1       ┆ 1    ┆ TOWEL    ┆ … ┆ obj           ┆ obj      ┆ 3        ┆ 1.517         │
│ 1       ┆ 1       ┆ 1    ┆ LADLE    ┆ … ┆ obj           ┆ obj      ┆ 3        ┆ 1.404         │
│ 1       ┆ 1       ┆ 1    ┆ THERMOS  ┆ … ┆ obj           ┆ obj      ┆ 3        ┆ 0.911         │
│ 1       ┆ 1       ┆ 1    ┆ LEGO     ┆ … ┆ obj           ┆ obj      ┆ 3        ┆ 0.883         │
│ 1       ┆ 1       ┆ 1    ┆ BACKPACK ┆ … ┆ obj           ┆ obj      ┆ 3        ┆ 0.819         │
└─────────┴─────────┴──────┴──────────┴───┴───────────────┴──────────┴──────────┴───────────────┘